language: node_js

cache: yarn

node_js:
  - 'stable'
  - '8'

sudo: false

script:
  - yarn test

after_script:
  - node_modules/.bin/coveralls < coverage/lcov.info

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      all_branches: true
      node: '8'
    skip_cleanup: true
